spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/course
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update

flyway:
  url: jdbc:postgresql://localhost:5432/course
  user: postgres
  password: 123456
  enabled: true
  locations:
    - 'classpath:db/migration'

api:
  server:
    url=http://localhost:8080